#################################
# Shadows
#################################

shadow = false;
shadow-radius = 18;
shadow-offset-x = -10;
shadow-offset-y = -10;
shadow-opacity = 0.20;

#################################
# Fading
#################################

fading = false;

#################################
# Opacity
#################################

inactive-opacity = 1;
active-opacity = 1;
frame-opacity = 1.0;

#################################
# Corners
#################################

corner-radius = 0;
rounded-corners-exclude = [
    "class_g = 'dwm'"
];

#################################
# Backend
#################################

backend = "glx";
vsync = true;

#################################
# Blur (disabled)
#################################

blur:
{
    method = "none";
};

#################################
# Misc
#################################

mark-wmwin-focused = true;
mark-ovredir-focused = true;
detect-rounded-corners = true;
detect-client-opacity = true;
use-damage = true;

#################################
# Animations
#################################

no-fading-openclose = false;
