include ~/.cache/wal/colors-kitty.conf

#####################
# Font
#####################

font_family      JetBrainsMono Nerd Font
bold_font        auto
italic_font      auto
bold_italic_font auto

font_size 15.0

#####################
# Window
#####################

window_padding_width 12

background_opacity 0.94

#####################
# Cursor
#####################

shell_intergration no-cursor
cursor_shape block
cursor_blink_interval 0

#####################
# Clipboard
#####################

copy_on_select yes

#####################
# Scrollback
#####################

scrollback_lines 100000

#####################
# Colors
#####################

cursor #f0e6d3
cursor_text_color #000000
