#!/bin/bash

WALLDIR="$HOME/pictures/wallpapers/"
wallpaper=$(nsxiv -to ${WALLDIR})

if [[ -z "$wallpaper" ]];then
	echo "Exiting"
	exit 
fi

feh --bg-fill ${wallpaper}

# Put it in .cache for xinitrc to use
CWALL="$HOME/.cache/current-wallpaper"
mkdir -p "$CWALL"
cp $wallpaper "$CWALL/current.jpg"

wal -i ${wallpaper} >/dev/null 2>&1

DWMDIR="$HOME/dotfiles/src/dwm/"
DWMCONF="$HOME/dotfiles/src/dwm/config.h"
DMENUDIR="$HOME/dotfiles/src/dmenu"
DMENUCONF="$HOME/dotfiles/src/dmenu/config.h"

if cd "$DWMDIR";then
	rm -f "$DWMCONF"
	sudo make clean install > /dev/null 2>&1
	kill -HUP $(pidof dwm)
else 
	echo
	echo "dir: $DWMDIR does not exist"
	echo "Could not compile dwm"
fi

if cd "$DMENUDIR";then
	rm -f "$DMENUCONF"
	sudo make clean install > /dev/null 2>&1
else
	echo 
	echo "dir:$DMENUDIR does not exist"
	echo "Could not recompile dmenu"
fi
